import LegalLayout from '@/components/LegalLayout';

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service">
      <p className="text-sm text-muted-foreground mb-6">
        Last updated: January 26, 2026
      </p>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">Introduction</h2>
        <p>
          Welcome to Lounge Learning. These Terms of Service ("Terms") govern your use of our IELTS preparation platform. By accessing or using our service, you agree to be bound by these Terms.
        </p>
        <p>
          If you do not agree to these Terms, please do not use our service.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">Use of Service</h2>
        <p>
          Our platform provides practice tests and AI-powered evaluation for IELTS preparation. You may use our service for personal, non-commercial purposes only.
        </p>
        <p className="font-bold text-red-600 bg-yellow-50 p-4 rounded-lg border-l-4 border-yellow-400">
          <strong>AI Accuracy Disclaimer:</strong> Estimated Band Scores are generated by AI for practice purposes only and do not guarantee results in official IELTS exams administered by IDP or British Council.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">User Accounts</h2>
        <p>
          To access certain features, you must create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
        </p>
        <p>
          You must provide accurate and complete information when creating your account.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">Fair Use and Prohibited Activities</h2>
        <p>
          You agree not to use bots, scripts, or automated tools to scrape or access our exam content. Such activities are strictly prohibited and may result in account suspension or termination.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">User Conduct</h2>
        <p>
          You agree to use our service responsibly and in compliance with applicable laws. We reserve the right to terminate your account for fraudulent activity or violation of these Terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">Content and Intellectual Property</h2>
        <p>
          All content on our platform, including test questions, materials, and AI-generated feedback, is owned by Lounge Learning or our licensors and is protected by copyright and other intellectual property laws.
        </p>
        <p>
          You may not reproduce, distribute, or create derivative works from our content without prior written permission.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">Payments</h2>
        <p>
          Some features of our platform may require payment for access. Premium features are digital products and are non-refundable once used or accessed.
        </p>
        <p>
          All payments are processed securely through our payment providers. Prices are subject to change with notice.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">Termination</h2>
        <p>
          We may terminate or suspend your account and access to our service at our discretion, with or without cause, and with or without notice.
        </p>
        <p>
          Upon termination, your right to use our service will cease immediately.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">Disclaimer of Warranties</h2>
        <p>
          Our service is provided "as is" without warranties of any kind. We do not guarantee that our service will be uninterrupted, error-free, or meet your specific requirements.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">Limitation of Liability</h2>
        <p>
          In no event shall Lounge Learning be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of our service.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">Changes to Terms</h2>
        <p>
          We may update these Terms from time to time. We will notify you of any changes by posting the new Terms on this page.
        </p>
        <p>
          Your continued use of our service after changes constitutes acceptance of the new Terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law provisions.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-foreground mb-4">Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us at:
        </p>
        <p className="mt-4">
          Email: lexoraielts@gmail.com<br />
          Address: Banepa-9, Kavre, Nepal
        </p>
      </section>
    </LegalLayout>
  );
}