import React from 'react';
import LegalLayout from '@/components/LegalLayout';

const TermsOfService: React.FC = () => {
  return (
    <LegalLayout title="Terms of Service">
      <section>
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
        <p className="mb-4">
          By accessing and using Learning Lounge, you accept and agree to be bound by the terms and provision of this agreement.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. Description of Service</h2>
        <p className="mb-4">
          Learning Lounge is an IELTS preparation platform that provides practice tests, evaluation, and learning resources to help users prepare for the IELTS exam.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. AI Accuracy Disclaimer</h2>
        <div className="bg-yellow-100 border-l-4 border-yellow-500 p-4 mb-4">
          <p className="font-bold text-yellow-800">
            <strong>Estimated Band Scores are generated by AI for practice purposes only and do not guarantee results in official IELTS exams administered by IDP or British Council.</strong>
          </p>
        </div>
        <p className="mb-4">
          Our AI-powered evaluations are designed to provide practice and feedback. They are not official IELTS scores and should not be used as a substitute for the actual exam.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. User Accounts</h2>
        <p className="mb-4">
          To access certain features, you must create an account. You are responsible for maintaining the confidentiality of your account information.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Fair Use and Prohibited Activities</h2>
        <p className="mb-4">
          You agree not to:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li>Use bots, scripts, or automated tools to scrape or access exam content</li>
          <li>Share your account credentials with others</li>
          <li>Attempt to reverse engineer or hack our platform</li>
          <li>Use the service for any illegal or unauthorized purpose</li>
        </ul>
      </section>

      <section>
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. User Conduct</h2>
        <p className="mb-4">
          We reserve the right to terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
        </p>
        <p className="mb-4">
          We may terminate accounts engaged in fraudulent activity or violation of these terms.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Premium Features and Payments</h2>
        <p className="mb-4">
          Premium features are digital services provided for a fee. Once a premium feature has been used or accessed, payments are non-refundable.
        </p>
        <p className="mb-4">
          All fees are non-refundable unless otherwise stated in writing.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Intellectual Property</h2>
        <p className="mb-4">
          The service and its original content, features, and functionality are and will remain the exclusive property of Learning Lounge and its licensors.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">9. Limitation of Liability</h2>
        <p className="mb-4">
          In no event shall Learning Lounge, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">10. Governing Law</h2>
        <p className="mb-4">
          These Terms shall be interpreted and governed by the laws of [Your Jurisdiction], without regard to its conflict of law provisions.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">11. Changes to Terms</h2>
        <p className="mb-4">
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will try to provide at least 30 days notice prior to any new terms taking effect.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold text-gray-900 mb-4">12. Contact Information</h2>
        <p className="mb-4">
          If you have any questions about these Terms of Service, please contact us at [your contact email].
        </p>
      </section>
    </LegalLayout>
  );
};

export default TermsOfService;